name: wordwise-front

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu:latest

    steps:
      - uses: actions/checkout@v4

      - name: 노드 세팅
        uses: actions/setup-node@v4
        with:
          node-version: $${{ secrets.NODE_VERSION }}

      - name: 의존성 설치
        run: npm install 

      - name: 정적 빌드
        run: npm run build

      - name: 빌드 파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USR }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./build/**"
          target: ${{ secrets.TARGET_PATH }}

      - name: 배포
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USR }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: ${{ secrets.TARGET_SCRIPT }}
